### ISSUE TITLE
Add packages to stackage

### ISSUE THREAD

**Issue by phadej** [dmwit/universe#14]
Would be nice to have these packages on [stackage](https://github.com/fpco/stackage#stackage). I'm considering using this packages as dependency for [lattices](http://hackage.haskell.org/package/lattices), but would like universe -family of packages to be on stackage first.

**Comment by dmwit** [comment]
You've got commit bit if you want to make it happen. My only request is that the cabal file's upper bounds stay (at least in master).

**Comment by phadej** [comment]
upper bounds are :+1:

**Comment by phadej** [comment]
And thanks for the commit bit, I'll carry the responsibility. Yet stackage cares about the version in the hackage :)

**Comment by dmwit** [comment]
Okay, Hackage should be in sync with the repo now.

**Comment by dmwit** [comment]
Ah, I just realized your last comment may have been a circumspect way of asking to be added to the maintainer list on Hackage. I'm happy to do that; what's your username? I tried to add OlegGrenrus, but that name doesn't seem to be used.

**Comment by phadej** [comment]
It's `phadej` on hackage as well :)

**Comment by dmwit** [comment]
Done.

**Comment by phadej** [comment]
Packages are added long ago, forgot to close this
