### ISSUE TITLE
container instances

### ISSUE THREAD

**Issue by phadej** [dmwit/universe#20]
Seems there is https://github.com/dmwit/universe/blob/32f1d4cf97a4699f60f2e5ede0415ce7502f3cd6/instances/containers/Data/Universe/Instances/Containers.hs but it's not done. I might need `Set` instance soon.

What about `unordered-containers` ? could they live in `universe-instances-containers` or would you prefer `universe-instances-unordered-containers`, @dmwit?

**Comment by dmwit** [comment]
I'm fine with either. I have a slight preference for the `universe-instances-<pkgname>` convention: it is consistent, and easily predictable for users who want to carefully manage their dependencies.

**Comment by dmwit** [comment]
...scratch that, it doesn't seem like I've been following that convention at all. Just "containers" seems fine.
