### ISSUE TITLE
Move Void instance to `universe-base`

### ISSUE THREAD

**Issue by phadej** [dmwit/universe#25]

**Comment by treeowl** [comment]
`Void`, `V1 a`, `()`, and `U1 a` are unusual in that each has *exactly one* lawful instance. So I don't see any reason for those even to be orphans.

**Comment by treeowl** [comment]
Also pretty boring: `instance Universe a => Universe (Identity a)`, `instance Universe a => Universe (Const a b)`, and `instance Universe a => Universe (K1 i a p)`.

**Comment by phadej** [comment]
Moved. Added Identity and Const. Will add generics later.
