### ISSUE TITLE
Should we offer a Generic helper?

### ISSUE THREAD

**Issue by treeowl** [dmwit/universe#40]
To a first approximation,

```haskell
class GUniverse f where
  gUniverse :: [f a]

instance GUniverse U1 where
  gUniverse = [U1]

instance GUniverse V1 where
  gUniverse = []

instance (GUniverse f, GUniverse g) => GUniverse (f :*: g) where
  gUniverse = map (\(x,y) -> x :*: y) $ gUniverse +*+ gUniverse

instance (GUniverse f, GUniverse g) => GUniverse (f :+: g) where
  gUniverse = map L1 gUniverse +++ map R1 gUniverse

instance GUniverse f => GUniverse (M1 i c f) where
  gUniverse = map M1 gUniverse

instance Universe c => GUniverse (K1 i c) where
  gUniverse = map K1 universe

universeGeneric :: (Generic a, GUniverse (Rep a)) => [a]
universeGeneric = map to gUniverse
```

**Comment by phadej** [comment]
Yes. Don't making it too clever has a change to work with recursive types, at the cost of not-so fair value production.

**Comment by treeowl** [comment]
@phadej, I'm having trouble parsing that sentence, unfortunately.

**Comment by phadej** [comment]
If we don't try to make it too clever, the generic implementation might work for recursive types.

**Comment by treeowl** [comment]
Yes, indeed. It should be a *bit* more clever, though. In particular, it should do something more "sum-of-products"-like. I'd expect it to interleave fairly among the constructors, and diagonally across the fields. The rough draft above is gratuitously unfair.

**Comment by phadej** [comment]
Offered in #41

**Comment by phadej** [comment]
And release is cut: https://hackage.haskell.org/package/universe-base-1.1 + others packages
